default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: localhost
  username: postgres
  password: daniel

development:
  <<: *default
  database: bridge_development

test:
  <<: *default
  database: bridge_test

production:
  <<: *default
  database: bridge_production
